name: publish

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Release
  BUILD_DIR : build
  LOGIN : ndesassis #${{secrets.TEST_PIPY_API_LOGIN}}
  PWD  : Nd79nd79. #${{secrets.TEST_PIPY_API_MDP}}
 
jobs:
   
  build:
    runs-on: ubuntu-latest
    container:
      image: ndesassis/testrepo
 
    steps:
      

    - uses: actions/checkout@v2
      
    - name : Create Wheels
      run : bash -eux deploy/pythonBuild.sh  ${{env.BUILD_DIR}}/python/${{env.BUILD_TYPE}}
      
    - name : Upload
    -  run : |
	python3 -m pip install twine 
	python3 -m twine upload ${{env.BUILD_DIR}}/python/${{env.BUILD_TYPE}}/dist/*
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.TWINE_TEST_TOKEN }}
        TWINE_REPOSITORY: testpypi

   

