name: publish

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  BUILD_DIR : build
 
jobs:
  
  build:
    runs-on: ubuntu-latest
    container:
      image: ndesassis/testrepo

    steps:
      

    - uses: actions/checkout@v2
      
    - name : deploy
      run : deploy/pythonBuild.sh


    - name: Publish distribution to Test PyPI
      working-directory : ${{env.BUILD_DIR}}
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.TEST_PYPI_MDP}}
        repository_url: https://test.pypi.org/legacy/


