name: publish

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  BUILD_DIR : build
 
jobs:
  
  build:
    runs-on: ubuntu-latest
    container:
      image: ndesassis/testrepo

    steps:
      

    - uses: actions/checkout@v2
      
    - name : deploy
      run : deploy/pythonBuild.sh

    - name : ls
      working-directory : ${{env.BUILD_DIR}}/python/${{env.BUILD_TYPE}}/
      run : ls 

    - name : ls
      working-directory : ${{env.BUILD_DIR}}/python/${{env.BUILD_TYPE}}/
      run : ls dist

    - name: publish
          env:
            TWINE_USERNAME: ${{ secrets.TEST_PIPY_API_LOGIN }}
            TWINE_PASSWORD: ${{ secrets.TEST_PIPY_API_MDP }}
          run: |
	    twine upload --repository testpypi ${{env.BUILD_DIR}}/python/${{env.BUILD_TYPE}}/dist/*

