name: publish

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Release
  BUILD_DIR : build
  LOGIN : ndesassis #${{secrets.TEST_PIPY_API_LOGIN}}
  PWD  : Nd79nd79. #${{secrets.TEST_PIPY_API_MDP}}
 
jobs:
   
  build:
    runs-on: ubuntu-latest
    container:
      image: ndesassis/testrepo
 
    steps:
      

    - uses: actions/checkout@v2
      
    - name : deploy
      run : |
        export PATH=/opt/python/cp39-cp39/bin/:$PATH
	python3 -m pip install twine
	cmake -Bbuild 
	cmake --build build --target python_build
	cd ${{env.BUILD_DIR}}/python/${{env.BUILD_TYPE}}
	python3 setup.py bdist_wheel --plat-name=manylinux_2_17_x86_64
	python3 -m twine upload --repository-url https://test.pypi.org/legacy/ --verbose dist/* -u ${{env.LOGIN}} -p ${{env.PWD}}




#bash -eux deploy/pythonBuild.sh  ${{env.BUILD_DIR}}/python/${{env.BUILD_TYPE}} ${{env.LOGIN}} ${{env.PWD}}
      

   

