name: publish

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  BUILD_DIR : build
 
jobs:
  
  build:
    runs-on: ubuntu-latest
    container:
      image: ndesassis/testrepo

    steps:
      

    - uses: actions/checkout@v2
      
    - name : deploy
      run : bash -eux deploy/pythonBuild.sh  ${{env.BUILD_DIR}}/python/${{env.BUILD_TYPE}} ${{secrets.TEST_PIPY_API_LOGIN }} ${{secrets.TEST_PIPY_API_MDP }}

  

